SQUARE_SIZE = 127

START_POSITION_FEN_W = 'rnbqkbnr/pppppppp/////PPPPPPPP/RNBQKBNR w KQkq -'
START_POSITION_FEN_B = 'RNBKQBNR/PPPPPPPP/////pppppppp/rnbkqbnr w KQkq -'

SCREEN_BG_COLOR = '#272521'
LIGHT_SQUARE_COLOR = '#7D955C'
DARK_SQUARE_COLOR = '#EEEFD4'
PICKED_SQUARE_COLOR = 'yellow'
PREV_SQUARE_COLOR = 'light blue'
NEXT_SQUARE_COLOR = 'blue'
LEGAL_MOVE_HIGHLIGHT_COLOR = 'light grey'
PREV_CORRECT_SQUARE_COLOR = 'light green'
NEXT_CORRECT_SQUARE_COLOR = 'green'

BUTTON_IDLE_COLOR = 'white'
BUTTON_HOVER_COLOR = 'light grey'
BUTTON_PRESSED_COLOR = 'grey'
BUTTON_INACTIVE_COLOR = 'dark grey'
BUTTON_SHADOW_COLOR = (100, 100, 100)

IMAGE_PATH = 'graphics/'
CHESS_PIECES_PATH = IMAGE_PATH + 'Chess-pieces/'

FONT = None
FONT_SIZE = 90
FONT_COLOR = '#231f20'

DATA_FILE = 'opening_data.json'

FRAME_RATE = 300
MOVE_ANIMATION_DURATION = FRAME_RATE // 3

LEARNING_STEPS = [1, 10, 1440] # minutes
NEW_INTERVAL_FACTOR = 0.5
HARD_INTERVAL_FACTOR = 1.2
LEARN_AHEAD_TIME = 30 # minutes

MENU_BUTTON_HEIGHT = 90
MENU_BUTTON_LENGTH = 700
BUTTON_BORDER_RADIUS = 20
BUTTON_PADDING = 5

TEXT_BOX_WIDTH = 750

# Again Review Button color palette
AGAIN_IDLE_COLOR = '#f94449'
AGAIN_HOVER_COLOR = '#f69697'
AGAIN_PRESSED_COLOR = '#ff2c2c'
AGAIN_SHADOW_COLOR = '#de0a26'

# Hard Review Button color palette 
HARD_IDLE_COLOR = '#d6e35a'
HARD_HOVER_COLOR = '#e7ef9e'
HARD_PRESSED_COLOR = '#ffe787'
HARD_SHADOW_COLOR = '#a09f28'

# Good Review Button color palette 
GOOD_IDLE_COLOR = '#5ced73'
GOOD_HOVER_COLOR = '#abf7b1'
GOOD_PRESSED_COLOR = '#39e75f'
GOOD_SHADOW_COLOR = '#008631'