SQUARE_SIZE = 127
WIDTH = SQUARE_SIZE * 8 + (SQUARE_SIZE * 4)
HEIGHT = SQUARE_SIZE * 8

LIGHT_SQUARE_COLOR = '#7D955C'
DARK_SQUARE_COLOR = '#EEEFD4'
PICKED_SQUARE_COLOR = 'yellow'
PREV_SQUARE_COLOR = 'light blue'
NEXT_SQUARE_COLOR = 'blue'
