SQUARE_SIZE = 127

SCREEN_BG_COLOR = '#272521'
LIGHT_SQUARE_COLOR = '#7D955C'
DARK_SQUARE_COLOR = '#EEEFD4'
PICKED_SQUARE_COLOR = 'yellow'
PREV_SQUARE_COLOR = 'light blue'
NEXT_SQUARE_COLOR = 'blue'
LEGAL_MOVE_HIGHLIGHT_COLOR = 'light grey'

IMAGE_PATH = 'graphics/'
CHESS_PIECES_PATH = IMAGE_PATH + 'Chess-pieces/'

FONT = None
FONT_SIZE = 90
FONT_COLOR = '#231f20'

DATA_FILE = 'data.json'

FRAME_RATE = 60
MOVE_ANIMATION_DURATION = 20